package postgres

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"

	"github.com/gopherex/iam/internal/domain"
)

// ErrNotFound / ErrConflict are the storage-level sentinels the service layer
// translates to its API errors. (IAM has no proto layer; records are stored as
// plain JSON in the `data` column.)
//
// ErrNotFound aliases domain.ErrNotFound so that an adapter which surfaces a
// no-rows result (directly or wrapped via translatePgErr) renders as a 404 at
// the API boundary instead of being masked as a 500 — errors.As in the ogen
// NewError hook finds the *domain.Error through the wrap. errors.Is checks
// against this sentinel keep working unchanged since it is the same value.
var (
	ErrNotFound error = domain.ErrNotFound
	ErrConflict       = errors.New("conflict")
)

// errAccountsNotPgCoreAuth guards the several places that type-assert the
// CoreAuthAccounts port back to *pgCoreAuth to reach its unexported helpers
// (both adapters live in this package, so the assertion is safe in practice).
// It should never actually fail; the sentinel exists so a broken wiring shows
// up as this specific error rather than an untyped panic-adjacent message.
var errAccountsNotPgCoreAuth = errors.New("accounts adapter is not *pgCoreAuth")

// randomTokenBytes is the byte length used for opaque random tokens/secrets
// across this package (256 bits): flow tokens, invite tokens, client secrets,
// CSRF/OIDC opaque values, and the like.
const randomTokenBytes = 32

// rsaKeyBits is the RSA modulus size used for self-signed SP/JWT signing keys
// generated by this package.
const rsaKeyBits = 2048

// httpStatusSuccessMin/Max bound the 2xx range this package treats as a
// successful outbound call (webhook delivery, hook invocation).
const (
	httpStatusSuccessMin = 200
	httpStatusSuccessMax = 300 // exclusive
)

func ptr[T any](v T) *T { return &v }

// marshal serializes a record to a JSONB blob.
func marshal(v any) ([]byte, error) { return json.Marshal(v) }

// unmarshal decodes a JSONB blob into v.
func unmarshal(b []byte, v any) error { return json.Unmarshal(b, v) }

// translatePgErr maps a no-rows error onto ErrNotFound; everything else passes
// through wrapped with the resource name. Both sentinels matter: generated PK
// finders surface the raw pgx.ErrNoRows, while the bob query builder (.One())
// wraps the driver in database/sql semantics and returns sql.ErrNoRows.
func translatePgErr(resource string, err error) error {
	if errors.Is(err, sql.ErrNoRows) || errors.Is(err, pgx.ErrNoRows) {
		return fmt.Errorf("%s: %w", resource, ErrNotFound)
	}

	return err
}

// isUniqueViolation reports whether err is a Postgres unique-constraint
// violation (SQLSTATE 23505), translated into ErrConflict by callers.
func isUniqueViolation(err error) bool {
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) {
		return pgErr.Code == "23505"
	}

	return false
}

// newUUID mints a fresh record id.
func newUUID() string { return uuid.NewString() }
