// Package api is the IAM API implementation: the hand-written code that
// consumers import. It satisfies the server interface generated by ogen
// (module-private under internal/oas) and re-exports the public surface so
// callers never import internal packages.
//
// The generated wire types/client/server live in internal/oas; this package
// is where our handler logic and public façade live. Handlers are filled in
// as the runtime stack is wired.
package api

import "github.com/gopherex/iam/internal/oas"

// Handler is the IAM server interface this package implements, re-exported from
// the generated code so importers depend only on pkg/api.
type Handler = oas.Handler

// Service implements Handler. Its methods are added as the stack is wired;
// once complete it will satisfy:
//
//	var _ Handler = (*Service)(nil)
type Service struct{}
