// Package api is the IAM API implementation: the hand-written code that
// consumers import. It satisfies the server interface generated by ogen
// (module-private under internal/oas) and re-exports the public surface so
// callers never import internal packages.
//
// The generated wire types/client/server live in internal/oas; this package
// is where our handler logic and public façade live. Handlers are filled in
// as the runtime stack is wired.
package api

import "github.com/gopherex/iam/internal/oas"

// Handler is the IAM server interface this package implements, re-exported from
// the generated code so importers depend only on pkg/api.
type Handler = oas.Handler

// The implementation is split per feature module: one XxxService per
// oas.<Group>Handler (core_auth.go, federation.go, admin.go, …). Each embeds
// oas.UnimplementedHandler — so any operation it does not override returns
// not-implemented — and panics on every v1.0.0 operation until written.
