// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleAdminToken handles adminToken security.
	// Project-admin token.
	HandleAdminToken(ctx context.Context, operationName OperationName, t AdminToken) (context.Context, error)
	// HandleBearerAuth handles bearerAuth security.
	// Bearer token. The concrete credential depends on the namespace:
	// user access token, service token / API key, project-admin token,
	// master key, or SCIM token.
	HandleBearerAuth(ctx context.Context, operationName OperationName, t BearerAuth) (context.Context, error)
	// HandleClientSecretBasic handles clientSecretBasic security.
	// OAuth client auth (client_secret_basic); client_secret_post / private_key_jwt also accepted in
	// body.
	HandleClientSecretBasic(ctx context.Context, operationName OperationName, t ClientSecretBasic) (context.Context, error)
	// HandleMasterKey handles masterKey security.
	// Operator master key (or operator-scoped credential).
	HandleMasterKey(ctx context.Context, operationName OperationName, t MasterKey) (context.Context, error)
	// HandleOAuth2 handles oauth2 security.
	// IAM as OAuth 2.0 / OIDC provider.
	HandleOAuth2(ctx context.Context, operationName OperationName, t OAuth2) (context.Context, error)
	// HandleScimToken handles scimToken security.
	// Per-connection SCIM bearer token.
	HandleScimToken(ctx context.Context, operationName OperationName, t ScimToken) (context.Context, error)
	// HandleServiceToken handles serviceToken security.
	// Service-account token or API key.
	HandleServiceToken(ctx context.Context, operationName OperationName, t ServiceToken) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesAdminToken is a private map storing roles per operation.
var operationRolesAdminToken = map[string][]string{
	DeleteV1ProjectsByProjectIdAdminApiKeysByKeyIdOperation:                         []string{},
	DeleteV1ProjectsByProjectIdAdminAppsByAppIdOperation:                            []string{},
	DeleteV1ProjectsByProjectIdAdminAppsByAppIdSecretsBySecretIdOperation:           []string{},
	DeleteV1ProjectsByProjectIdAdminDomainsByDomainIdOperation:                      []string{},
	DeleteV1ProjectsByProjectIdAdminEmailProvidersByIdOperation:                     []string{},
	DeleteV1ProjectsByProjectIdAdminHooksByIdOperation:                              []string{},
	DeleteV1ProjectsByProjectIdAdminJwksByKeyIdOperation:                            []string{},
	DeleteV1ProjectsByProjectIdAdminOauthProvidersByIdOperation:                     []string{},
	DeleteV1ProjectsByProjectIdAdminRateLimitBlocksByBlockIdOperation:               []string{},
	DeleteV1ProjectsByProjectIdAdminRiskRulesByRuleIdOperation:                      []string{},
	DeleteV1ProjectsByProjectIdAdminServiceAccountsBySaIdOperation:                  []string{},
	DeleteV1ProjectsByProjectIdAdminServiceAccountsBySaIdSecretsBySecretIdOperation: []string{},
	DeleteV1ProjectsByProjectIdAdminSmsProvidersByIdOperation:                       []string{},
	DeleteV1ProjectsByProjectIdAdminSsoConnectionsByIdOperation:                     []string{},
	DeleteV1ProjectsByProjectIdAdminSsoConnectionsByIdScimTokensByTokenIdOperation:  []string{},
	DeleteV1ProjectsByProjectIdAdminTokenProfilesByIdOperation:                      []string{},
	DeleteV1ProjectsByProjectIdAdminUsersByUserIdOperation:                          []string{},
	DeleteV1ProjectsByProjectIdAdminUsersByUserIdGrantsByGrantIdOperation:           []string{},
	DeleteV1ProjectsByProjectIdAdminUsersByUserIdIdentitiesByIdentityIdOperation:    []string{},
	DeleteV1ProjectsByProjectIdAdminUsersByUserIdSessionsBySessionIdOperation:       []string{},
	DeleteV1ProjectsByProjectIdAdminWebhooksByIdOperation:                           []string{},
	GetV1ProjectsByProjectIdAdminAccessRequestsOperation:                            []string{},
	GetV1ProjectsByProjectIdAdminApiKeysOperation:                                   []string{},
	GetV1ProjectsByProjectIdAdminAppsOperation:                                      []string{},
	GetV1ProjectsByProjectIdAdminAppsByAppIdOperation:                               []string{},
	GetV1ProjectsByProjectIdAdminAuditLogsOperation:                                 []string{},
	GetV1ProjectsByProjectIdAdminAuditLogsByAuditIdOperation:                        []string{},
	GetV1ProjectsByProjectIdAdminConfigAuthOperation:                                []string{},
	GetV1ProjectsByProjectIdAdminConfigMfaPolicyOperation:                           []string{},
	GetV1ProjectsByProjectIdAdminConfigPasswordPolicyOperation:                      []string{},
	GetV1ProjectsByProjectIdAdminConfigRateLimitsOperation:                          []string{},
	GetV1ProjectsByProjectIdAdminConfigSessionPolicyOperation:                       []string{},
	GetV1ProjectsByProjectIdAdminConsentsOperation:                                  []string{},
	GetV1ProjectsByProjectIdAdminDomainsOperation:                                   []string{},
	GetV1ProjectsByProjectIdAdminEmailProvidersOperation:                            []string{},
	GetV1ProjectsByProjectIdAdminEmailTemplatesOperation:                            []string{},
	GetV1ProjectsByProjectIdAdminEventsOperation:                                    []string{},
	GetV1ProjectsByProjectIdAdminExportsByJobIdOperation:                            []string{},
	GetV1ProjectsByProjectIdAdminFeaturesOperation:                                  []string{},
	GetV1ProjectsByProjectIdAdminHooksOperation:                                     []string{},
	GetV1ProjectsByProjectIdAdminI18nByLocaleOperation:                              []string{},
	GetV1ProjectsByProjectIdAdminJobsOperation:                                      []string{},
	GetV1ProjectsByProjectIdAdminJobsByJobIdOperation:                               []string{},
	GetV1ProjectsByProjectIdAdminJwksOperation:                                      []string{},
	GetV1ProjectsByProjectIdAdminOauthProvidersOperation:                            []string{},
	GetV1ProjectsByProjectIdAdminRetentionPolicyOperation:                           []string{},
	GetV1ProjectsByProjectIdAdminRiskEventsOperation:                                []string{},
	GetV1ProjectsByProjectIdAdminRiskRulesOperation:                                 []string{},
	GetV1ProjectsByProjectIdAdminServiceAccountsOperation:                           []string{},
	GetV1ProjectsByProjectIdAdminServiceAccountsBySaIdOperation:                     []string{},
	GetV1ProjectsByProjectIdAdminSmsProvidersOperation:                              []string{},
	GetV1ProjectsByProjectIdAdminSsoConnectionsOperation:                            []string{},
	GetV1ProjectsByProjectIdAdminSsoConnectionsByIdOperation:                        []string{},
	GetV1ProjectsByProjectIdAdminSsoConnectionsByIdScimTokensOperation:              []string{},
	GetV1ProjectsByProjectIdAdminTokenProfilesOperation:                             []string{},
	GetV1ProjectsByProjectIdAdminUsersOperation:                                     []string{},
	GetV1ProjectsByProjectIdAdminUsersByUserIdOperation:                             []string{},
	GetV1ProjectsByProjectIdAdminUsersByUserIdGrantsOperation:                       []string{},
	GetV1ProjectsByProjectIdAdminUsersByUserIdIdentitiesOperation:                   []string{},
	GetV1ProjectsByProjectIdAdminUsersByUserIdSessionsOperation:                     []string{},
	GetV1ProjectsByProjectIdAdminWebhookDeliveriesOperation:                         []string{},
	GetV1ProjectsByProjectIdAdminWebhooksOperation:                                  []string{},
	GetV1ProjectsByProjectIdAdminWebhooksByIdOperation:                              []string{},
	GetV1TestMessagesOperation:                                                      []string{},
	PatchV1ProjectsByProjectIdAdminApiKeysByKeyIdOperation:                          []string{},
	PatchV1ProjectsByProjectIdAdminAppsByAppIdOperation:                             []string{},
	PatchV1ProjectsByProjectIdAdminConfigAuthOperation:                              []string{},
	PatchV1ProjectsByProjectIdAdminConfigMfaPolicyOperation:                         []string{},
	PatchV1ProjectsByProjectIdAdminConfigPasswordPolicyOperation:                    []string{},
	PatchV1ProjectsByProjectIdAdminConfigRateLimitsOperation:                        []string{},
	PatchV1ProjectsByProjectIdAdminConfigSessionPolicyOperation:                     []string{},
	PatchV1ProjectsByProjectIdAdminEmailProvidersByIdOperation:                      []string{},
	PatchV1ProjectsByProjectIdAdminEmailTemplatesByIdOperation:                      []string{},
	PatchV1ProjectsByProjectIdAdminHooksByIdOperation:                               []string{},
	PatchV1ProjectsByProjectIdAdminOauthProvidersByIdOperation:                      []string{},
	PatchV1ProjectsByProjectIdAdminRiskRulesByRuleIdOperation:                       []string{},
	PatchV1ProjectsByProjectIdAdminServiceAccountsBySaIdOperation:                   []string{},
	PatchV1ProjectsByProjectIdAdminSmsProvidersByIdOperation:                        []string{},
	PatchV1ProjectsByProjectIdAdminSsoConnectionsByIdOperation:                      []string{},
	PatchV1ProjectsByProjectIdAdminTokenProfilesByIdOperation:                       []string{},
	PatchV1ProjectsByProjectIdAdminUsersByUserIdOperation:                           []string{},
	PatchV1ProjectsByProjectIdAdminWebhooksByIdOperation:                            []string{},
	PostV1ProjectsByProjectIdAdminAccessRequestsByIdApproveOperation:                []string{},
	PostV1ProjectsByProjectIdAdminAccessRequestsByIdDenyOperation:                   []string{},
	PostV1ProjectsByProjectIdAdminApiKeysOperation:                                  []string{},
	PostV1ProjectsByProjectIdAdminApiKeysByKeyIdRotateOperation:                     []string{},
	PostV1ProjectsByProjectIdAdminAppsOperation:                                     []string{},
	PostV1ProjectsByProjectIdAdminAppsByAppIdSecretsOperation:                       []string{},
	PostV1ProjectsByProjectIdAdminAuditExportOperation:                              []string{},
	PostV1ProjectsByProjectIdAdminDomainsOperation:                                  []string{},
	PostV1ProjectsByProjectIdAdminDomainsByDomainIdVerifyOperation:                  []string{},
	PostV1ProjectsByProjectIdAdminEmailProvidersOperation:                           []string{},
	PostV1ProjectsByProjectIdAdminEmailTemplatesByIdPreviewOperation:                []string{},
	PostV1ProjectsByProjectIdAdminEmailTemplatesByIdSendTestOperation:               []string{},
	PostV1ProjectsByProjectIdAdminEventsByEventIdReplayOperation:                    []string{},
	PostV1ProjectsByProjectIdAdminHooksOperation:                                    []string{},
	PostV1ProjectsByProjectIdAdminHooksByIdTestOperation:                            []string{},
	PostV1ProjectsByProjectIdAdminImportPasswordHashesVerifyOperation:               []string{},
	PostV1ProjectsByProjectIdAdminImportUsersOperation:                              []string{},
	PostV1ProjectsByProjectIdAdminJobsByJobIdCancelOperation:                        []string{},
	PostV1ProjectsByProjectIdAdminJwksByKeyIdActivateOperation:                      []string{},
	PostV1ProjectsByProjectIdAdminJwksRotateOperation:                               []string{},
	PostV1ProjectsByProjectIdAdminOauthProvidersOperation:                           []string{},
	PostV1ProjectsByProjectIdAdminRateLimitBlocksOperation:                          []string{},
	PostV1ProjectsByProjectIdAdminRiskRulesOperation:                                []string{},
	PostV1ProjectsByProjectIdAdminServiceAccountsOperation:                          []string{},
	PostV1ProjectsByProjectIdAdminServiceAccountsBySaIdSecretsOperation:             []string{},
	PostV1ProjectsByProjectIdAdminSmsProvidersOperation:                             []string{},
	PostV1ProjectsByProjectIdAdminSsoConnectionsOperation:                           []string{},
	PostV1ProjectsByProjectIdAdminSsoConnectionsByIdRotateCertificateOperation:      []string{},
	PostV1ProjectsByProjectIdAdminSsoConnectionsByIdScimTokensOperation:             []string{},
	PostV1ProjectsByProjectIdAdminSsoConnectionsByIdTestOperation:                   []string{},
	PostV1ProjectsByProjectIdAdminTokenProfilesOperation:                            []string{},
	PostV1ProjectsByProjectIdAdminTokenProfilesByIdPreviewOperation:                 []string{},
	PostV1ProjectsByProjectIdAdminUsersOperation:                                    []string{},
	PostV1ProjectsByProjectIdAdminUsersByUserIdAnonymizeOperation:                   []string{},
	PostV1ProjectsByProjectIdAdminUsersByUserIdBanOperation:                         []string{},
	PostV1ProjectsByProjectIdAdminUsersByUserIdExportOperation:                      []string{},
	PostV1ProjectsByProjectIdAdminUsersByUserIdImpersonateOperation:                 []string{},
	PostV1ProjectsByProjectIdAdminUsersByUserIdMfaResetOperation:                    []string{},
	PostV1ProjectsByProjectIdAdminUsersByUserIdPasswordOperation:                    []string{},
	PostV1ProjectsByProjectIdAdminUsersByUserIdSessionsRevokeOperation:              []string{},
	PostV1ProjectsByProjectIdAdminUsersByUserIdUnbanOperation:                       []string{},
	PostV1ProjectsByProjectIdAdminUsersByUserIdVerifyEmailOperation:                 []string{},
	PostV1ProjectsByProjectIdAdminUsersByUserIdVerifyPhoneOperation:                 []string{},
	PostV1ProjectsByProjectIdAdminWebhookDeliveriesByDeliveryIdRetryOperation:       []string{},
	PostV1ProjectsByProjectIdAdminWebhooksOperation:                                 []string{},
	PostV1ProjectsByProjectIdAdminWebhooksByIdRotateSecretOperation:                 []string{},
	PostV1ProjectsByProjectIdAdminWebhooksByIdTestOperation:                         []string{},
	PostV1TestClockOperation:                                                        []string{},
	PostV1TestResetOperation:                                                        []string{},
	PostV1TestSeedOperation:                                                         []string{},
	PutV1ProjectsByProjectIdAdminConsentsOperation:                                  []string{},
	PutV1ProjectsByProjectIdAdminFeaturesOperation:                                  []string{},
	PutV1ProjectsByProjectIdAdminI18nByLocaleOperation:                              []string{},
	PutV1ProjectsByProjectIdAdminRetentionPolicyOperation:                           []string{},
}

// GetRolesForAdminToken returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForAdminToken(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForAdminToken(operation string) []string {
	roles, ok := operationRolesAdminToken[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesBearerAuth is a private map storing roles per operation.
var operationRolesBearerAuth = map[string][]string{
	DeleteV1AuthIdentitiesByIdentityIdOperation:            []string{},
	DeleteV1AuthMfaFactorsByFactorIdOperation:              []string{},
	DeleteV1AuthWebauthnCredentialsByCredentialIdOperation: []string{},
	DeleteV1OauthGrantsByGrantIdOperation:                  []string{},
	DeleteV1SessionsOperation:                              []string{},
	DeleteV1SessionsBySessionIdOperation:                   []string{},
	DeleteV1UsersMeOperation:                               []string{},
	GetOauth2UserinfoOperation:                             []string{},
	GetV1AccountCapabilitiesOperation:                      []string{},
	GetV1AuthIdentitiesOperation:                           []string{},
	GetV1AuthMfaFactorsOperation:                           []string{},
	GetV1AuthOauthByProviderLinkStartOperation:             []string{},
	GetV1AuthSessionOperation:                              []string{},
	GetV1AuthWebauthnCredentialsOperation:                  []string{},
	GetV1OauthGrantsOperation:                              []string{},
	GetV1SessionsOperation:                                 []string{},
	GetV1SessionsCurrentOperation:                          []string{},
	GetV1TokensCurrentOperation:                            []string{},
	GetV1UsersMeOperation:                                  []string{},
	GetV1UsersMeActivityOperation:                          []string{},
	GetV1UsersMeConsentsOperation:                          []string{},
	GetV1UsersMeExportByJobIdOperation:                     []string{},
	PatchV1AuthWebauthnCredentialsByCredentialIdOperation:  []string{},
	PatchV1SessionsBySessionIdOperation:                    []string{},
	PatchV1UsersMeOperation:                                []string{},
	PostV1AuthEmailChangeStartOperation:                    []string{},
	PostV1AuthEmailChangeVerifyOperation:                   []string{},
	PostV1AuthIdentitiesMergeConfirmOperation:              []string{},
	PostV1AuthIdentitiesMergeStartOperation:                []string{},
	PostV1AuthMfaEmailEnrollOperation:                      []string{},
	PostV1AuthMfaRecoveryCodesGenerateOperation:            []string{},
	PostV1AuthMfaSmsEnrollOperation:                        []string{},
	PostV1AuthMfaTotpEnrollOperation:                       []string{},
	PostV1AuthMfaTotpVerifyOperation:                       []string{},
	PostV1AuthMfaWebauthnEnrollOptionsOperation:            []string{},
	PostV1AuthMfaWebauthnEnrollVerifyOperation:             []string{},
	PostV1AuthOauthByProviderUnlinkOperation:               []string{},
	PostV1AuthPasswordChangeOperation:                      []string{},
	PostV1AuthPasswordVerifyOperation:                      []string{},
	PostV1AuthPhoneChangeStartOperation:                    []string{},
	PostV1AuthPhoneChangeVerifyOperation:                   []string{},
	PostV1AuthSessionStepUpOperation:                       []string{},
	PostV1AuthSessionSwitchGroupOperation:                  []string{},
	PostV1AuthSignOutOperation:                             []string{},
	PostV1AuthSignOutAllOperation:                          []string{},
	PostV1AuthWebauthnRegisterOptionsOperation:             []string{},
	PostV1AuthWebauthnRegisterVerifyOperation:              []string{},
	PostV1DeviceApproveOperation:                           []string{},
	PostV1DeviceDenyOperation:                              []string{},
	PostV1OauthInteractionByInteractionIdConsentOperation:  []string{},
	PostV1OauthInteractionByInteractionIdLoginOperation:    []string{},
	PostV1SessionsBySessionIdTrustOperation:                []string{},
	PostV1TokensIntrospectOperation:                        []string{},
	PostV1TokensRevokeOperation:                            []string{},
	PostV1TokensVerifyOperation:                            []string{},
	PostV1UsersMeConsentsOperation:                         []string{},
	PostV1UsersMeExportOperation:                           []string{},
}

// GetRolesForBearerAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForBearerAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForBearerAuth(operation string) []string {
	roles, ok := operationRolesBearerAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesClientSecretBasic is a private map storing roles per operation.
var operationRolesClientSecretBasic = map[string][]string{
	PostOauth2DeviceAuthorizationOperation: []string{},
	PostOauth2IntrospectOperation:          []string{},
	PostOauth2ParOperation:                 []string{},
	PostOauth2RevokeOperation:              []string{},
	PostOauth2TokenOperation:               []string{},
}

// GetRolesForClientSecretBasic returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForClientSecretBasic(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForClientSecretBasic(operation string) []string {
	roles, ok := operationRolesClientSecretBasic[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesMasterKey is a private map storing roles per operation.
var operationRolesMasterKey = map[string][]string{
	DeleteMgmtV1ProjectsByProjectIdOperation:                     []string{},
	DeleteMgmtV1ProjectsByProjectIdAdminTokensByTokenIdOperation: []string{},
	DeleteMgmtV1ProjectsByProjectIdEnvironmentsByEnvOperation:    []string{},
	GetMgmtV1ProjectsOperation:                                   []string{},
	GetMgmtV1ProjectsByProjectIdOperation:                        []string{},
	GetMgmtV1ProjectsByProjectIdAdminTokensOperation:             []string{},
	GetMgmtV1ProjectsByProjectIdConfigExportOperation:            []string{},
	GetMgmtV1ProjectsByProjectIdEnvironmentsOperation:            []string{},
	GetMgmtV1ProjectsByProjectIdEnvironmentsByEnvOperation:       []string{},
	GetMgmtV1ProjectsByProjectIdFeaturesOperation:                []string{},
	PatchMgmtV1ProjectsByProjectIdOperation:                      []string{},
	PatchMgmtV1ProjectsByProjectIdFeaturesOperation:              []string{},
	PostMgmtV1ProjectsOperation:                                  []string{},
	PostMgmtV1ProjectsByProjectIdAdminTokensOperation:            []string{},
	PostMgmtV1ProjectsByProjectIdConfigApplyOperation:            []string{},
	PostMgmtV1ProjectsByProjectIdConfigPlanOperation:             []string{},
	PostMgmtV1ProjectsByProjectIdEnvironmentsOperation:           []string{},
}

// GetRolesForMasterKey returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForMasterKey(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForMasterKey(operation string) []string {
	roles, ok := operationRolesMasterKey[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// oauth2ScopesOAuth2 is a private map storing OAuth2 scopes per operation.
var oauth2ScopesOAuth2 = map[string][]string{
	GetOauth2UserinfoOperation: []string{
		"openid",
	},
}

// GetOAuth2ScopesForOAuth2 returns the required OAuth2 scopes for the given operation.
//
// This is useful for token exchange scenarios where you need to know which scopes
// to request when obtaining a token for a downstream API call.
//
// Example:
//
//	requiredScopes := GetOAuth2ScopesForOAuth2(AddPetOperation)
//	token := exchangeTokenWithScopes(requiredScopes, "https://api.example.com")
//
// Returns nil if the operation has no scope requirements or if the operation is unknown.
func GetOAuth2ScopesForOAuth2(operation string) []string {
	scopes, ok := oauth2ScopesOAuth2[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(scopes))
	copy(result, scopes)
	return result
}

// operationRolesScimToken is a private map storing roles per operation.
var operationRolesScimToken = map[string][]string{
	DeleteV1ScimV2ByConnectionIdGroupsByGroupIdOperation:   []string{},
	DeleteV1ScimV2ByConnectionIdUsersByScimUserIdOperation: []string{},
	GetV1ScimV2ByConnectionIdGroupsOperation:               []string{},
	GetV1ScimV2ByConnectionIdGroupsByGroupIdOperation:      []string{},
	GetV1ScimV2ByConnectionIdUsersOperation:                []string{},
	GetV1ScimV2ByConnectionIdUsersByScimUserIdOperation:    []string{},
	PatchV1ScimV2ByConnectionIdGroupsByGroupIdOperation:    []string{},
	PatchV1ScimV2ByConnectionIdUsersByScimUserIdOperation:  []string{},
	PostV1ScimV2ByConnectionIdGroupsOperation:              []string{},
	PostV1ScimV2ByConnectionIdUsersOperation:               []string{},
	PutV1ScimV2ByConnectionIdGroupsByGroupIdOperation:      []string{},
	PutV1ScimV2ByConnectionIdUsersByScimUserIdOperation:    []string{},
}

// GetRolesForScimToken returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForScimToken(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForScimToken(operation string) []string {
	roles, ok := operationRolesScimToken[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesServiceToken is a private map storing roles per operation.
var operationRolesServiceToken = map[string][]string{
	PostV1ServiceAccountsTokensOperation: []string{},
}

// GetRolesForServiceToken returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForServiceToken(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForServiceToken(operation string) []string {
	roles, ok := operationRolesServiceToken[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityAdminToken(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t AdminToken
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesAdminToken[operationName]
	rctx, err := s.sec.HandleAdminToken(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t BearerAuth
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesBearerAuth[operationName]
	rctx, err := s.sec.HandleBearerAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityClientSecretBasic(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t ClientSecretBasic
	if _, ok := findAuthorization(req.Header, "Basic"); !ok {
		return ctx, false, nil
	}
	username, password, ok := req.BasicAuth()
	if !ok {
		return nil, false, errors.New("invalid basic auth")
	}
	t.Username = username
	t.Password = password
	t.Roles = operationRolesClientSecretBasic[operationName]
	rctx, err := s.sec.HandleClientSecretBasic(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityMasterKey(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t MasterKey
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesMasterKey[operationName]
	rctx, err := s.sec.HandleMasterKey(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityOAuth2(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t OAuth2
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Scopes = oauth2ScopesOAuth2[operationName]
	rctx, err := s.sec.HandleOAuth2(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityScimToken(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t ScimToken
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesScimToken[operationName]
	rctx, err := s.sec.HandleScimToken(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityServiceToken(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t ServiceToken
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesServiceToken[operationName]
	rctx, err := s.sec.HandleServiceToken(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// AdminToken provides adminToken security value.
	// Project-admin token.
	AdminToken(ctx context.Context, operationName OperationName, client *Client) (AdminToken, error)
	// BearerAuth provides bearerAuth security value.
	// Bearer token. The concrete credential depends on the namespace:
	// user access token, service token / API key, project-admin token,
	// master key, or SCIM token.
	BearerAuth(ctx context.Context, operationName OperationName, client *Client) (BearerAuth, error)
	// ClientSecretBasic provides clientSecretBasic security value.
	// OAuth client auth (client_secret_basic); client_secret_post / private_key_jwt also accepted in
	// body.
	ClientSecretBasic(ctx context.Context, operationName OperationName, client *Client) (ClientSecretBasic, error)
	// MasterKey provides masterKey security value.
	// Operator master key (or operator-scoped credential).
	MasterKey(ctx context.Context, operationName OperationName, client *Client) (MasterKey, error)
	// OAuth2 provides oauth2 security value.
	// IAM as OAuth 2.0 / OIDC provider.
	OAuth2(ctx context.Context, operationName OperationName, client *Client) (OAuth2, error)
	// ScimToken provides scimToken security value.
	// Per-connection SCIM bearer token.
	ScimToken(ctx context.Context, operationName OperationName, client *Client) (ScimToken, error)
	// ServiceToken provides serviceToken security value.
	// Service-account token or API key.
	ServiceToken(ctx context.Context, operationName OperationName, client *Client) (ServiceToken, error)
}

func (s *Client) securityAdminToken(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.AdminToken(ctx, operationName, s)
	if err != nil {
		return errors.Wrap(err, "security source \"AdminToken\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BearerAuth(ctx, operationName, s)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityClientSecretBasic(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ClientSecretBasic(ctx, operationName, s)
	if err != nil {
		return errors.Wrap(err, "security source \"ClientSecretBasic\"")
	}
	req.SetBasicAuth(t.Username, t.Password)
	return nil
}
func (s *Client) securityMasterKey(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.MasterKey(ctx, operationName, s)
	if err != nil {
		return errors.Wrap(err, "security source \"MasterKey\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityOAuth2(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.OAuth2(ctx, operationName, s)
	if err != nil {
		return errors.Wrap(err, "security source \"OAuth2\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityScimToken(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ScimToken(ctx, operationName, s)
	if err != nil {
		return errors.Wrap(err, "security source \"ScimToken\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityServiceToken(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ServiceToken(ctx, operationName, s)
	if err != nil {
		return errors.Wrap(err, "security source \"ServiceToken\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
