// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *DeleteV1SessionsReq) setDefaults() {
	{
		val := bool(true)
		s.ExceptCurrent.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PasswordChangeRequest) setDefaults() {
	{
		val := bool(false)
		s.RevokeOtherSessions.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PostV1AuthMfaRecoveryCodesGenerateReq) setDefaults() {
	{
		val := bool(false)
		s.Regenerate.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PostV1AuthPhoneChangeStartReq) setDefaults() {
	{
		val := PostV1AuthPhoneChangeStartReqChannel("sms")
		s.Channel.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PostV1AuthPhoneVerificationStartReq) setDefaults() {
	{
		val := PostV1AuthPhoneVerificationStartReqChannel("sms")
		s.Channel.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PostV1AuthSignOutAllReq) setDefaults() {
	{
		val := bool(true)
		s.ExceptCurrent.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PostV1AuthSignOutReq) setDefaults() {
	{
		val := bool(false)
		s.Everywhere.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PostV1ProjectsByProjectIdAdminJwksRotateReq) setDefaults() {
	{
		val := bool(false)
		s.Activate.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PostV1ServiceAccountsTokensReq) setDefaults() {
	{
		val := int(600)
		s.TTLSeconds.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SignUpRequest) setDefaults() {
	{
		val := bool(false)
		s.Test.SetTo(val)
	}
}
