// Code generated by ogen, DO NOT EDIT.
package api

type DeleteMgmtV1ProjectsByProjectIdAdminTokensByTokenIdRes interface {
	deleteMgmtV1ProjectsByProjectIdAdminTokensByTokenIdRes()
}

type DeleteMgmtV1ProjectsByProjectIdEnvironmentsByEnvRes interface {
	deleteMgmtV1ProjectsByProjectIdEnvironmentsByEnvRes()
}

type DeleteMgmtV1ProjectsByProjectIdRes interface {
	deleteMgmtV1ProjectsByProjectIdRes()
}

type DeleteV1AuthIdentitiesByIdentityIdRes interface {
	deleteV1AuthIdentitiesByIdentityIdRes()
}

type DeleteV1AuthMfaFactorsByFactorIdRes interface {
	deleteV1AuthMfaFactorsByFactorIdRes()
}

type DeleteV1AuthWebauthnCredentialsByCredentialIdRes interface {
	deleteV1AuthWebauthnCredentialsByCredentialIdRes()
}

type DeleteV1OauthGrantsByGrantIdRes interface {
	deleteV1OauthGrantsByGrantIdRes()
}

type DeleteV1ProjectsByProjectIdAdminApiKeysByKeyIdRes interface {
	deleteV1ProjectsByProjectIdAdminApiKeysByKeyIdRes()
}

type DeleteV1ProjectsByProjectIdAdminAppsByAppIdRes interface {
	deleteV1ProjectsByProjectIdAdminAppsByAppIdRes()
}

type DeleteV1ProjectsByProjectIdAdminAppsByAppIdSecretsBySecretIdRes interface {
	deleteV1ProjectsByProjectIdAdminAppsByAppIdSecretsBySecretIdRes()
}

type DeleteV1ProjectsByProjectIdAdminDomainsByDomainIdRes interface {
	deleteV1ProjectsByProjectIdAdminDomainsByDomainIdRes()
}

type DeleteV1ProjectsByProjectIdAdminEmailProvidersByIdRes interface {
	deleteV1ProjectsByProjectIdAdminEmailProvidersByIdRes()
}

type DeleteV1ProjectsByProjectIdAdminHooksByIdRes interface {
	deleteV1ProjectsByProjectIdAdminHooksByIdRes()
}

type DeleteV1ProjectsByProjectIdAdminJwksByKeyIdRes interface {
	deleteV1ProjectsByProjectIdAdminJwksByKeyIdRes()
}

type DeleteV1ProjectsByProjectIdAdminOauthProvidersByIdRes interface {
	deleteV1ProjectsByProjectIdAdminOauthProvidersByIdRes()
}

type DeleteV1ProjectsByProjectIdAdminRateLimitBlocksByBlockIdRes interface {
	deleteV1ProjectsByProjectIdAdminRateLimitBlocksByBlockIdRes()
}

type DeleteV1ProjectsByProjectIdAdminRiskRulesByRuleIdRes interface {
	deleteV1ProjectsByProjectIdAdminRiskRulesByRuleIdRes()
}

type DeleteV1ProjectsByProjectIdAdminServiceAccountsBySaIdRes interface {
	deleteV1ProjectsByProjectIdAdminServiceAccountsBySaIdRes()
}

type DeleteV1ProjectsByProjectIdAdminServiceAccountsBySaIdSecretsBySecretIdRes interface {
	deleteV1ProjectsByProjectIdAdminServiceAccountsBySaIdSecretsBySecretIdRes()
}

type DeleteV1ProjectsByProjectIdAdminSmsProvidersByIdRes interface {
	deleteV1ProjectsByProjectIdAdminSmsProvidersByIdRes()
}

type DeleteV1ProjectsByProjectIdAdminSsoConnectionsByIdRes interface {
	deleteV1ProjectsByProjectIdAdminSsoConnectionsByIdRes()
}

type DeleteV1ProjectsByProjectIdAdminSsoConnectionsByIdScimTokensByTokenIdRes interface {
	deleteV1ProjectsByProjectIdAdminSsoConnectionsByIdScimTokensByTokenIdRes()
}

type DeleteV1ProjectsByProjectIdAdminTokenProfilesByIdRes interface {
	deleteV1ProjectsByProjectIdAdminTokenProfilesByIdRes()
}

type DeleteV1ProjectsByProjectIdAdminUsersByUserIdGrantsByGrantIdRes interface {
	deleteV1ProjectsByProjectIdAdminUsersByUserIdGrantsByGrantIdRes()
}

type DeleteV1ProjectsByProjectIdAdminUsersByUserIdIdentitiesByIdentityIdRes interface {
	deleteV1ProjectsByProjectIdAdminUsersByUserIdIdentitiesByIdentityIdRes()
}

type DeleteV1ProjectsByProjectIdAdminUsersByUserIdRes interface {
	deleteV1ProjectsByProjectIdAdminUsersByUserIdRes()
}

type DeleteV1ProjectsByProjectIdAdminUsersByUserIdSessionsBySessionIdRes interface {
	deleteV1ProjectsByProjectIdAdminUsersByUserIdSessionsBySessionIdRes()
}

type DeleteV1ProjectsByProjectIdAdminWebhooksByIdRes interface {
	deleteV1ProjectsByProjectIdAdminWebhooksByIdRes()
}

type DeleteV1ScimV2ByConnectionIdGroupsByGroupIdRes interface {
	deleteV1ScimV2ByConnectionIdGroupsByGroupIdRes()
}

type DeleteV1ScimV2ByConnectionIdUsersByScimUserIdRes interface {
	deleteV1ScimV2ByConnectionIdUsersByScimUserIdRes()
}

type DeleteV1SessionsBySessionIdRes interface {
	deleteV1SessionsBySessionIdRes()
}

type DeleteV1SessionsRes interface {
	deleteV1SessionsRes()
}

type DeleteV1UsersMeRes interface {
	deleteV1UsersMeRes()
}

type GetMgmtV1ProjectsByProjectIdAdminTokensRes interface {
	getMgmtV1ProjectsByProjectIdAdminTokensRes()
}

type GetMgmtV1ProjectsByProjectIdConfigExportRes interface {
	getMgmtV1ProjectsByProjectIdConfigExportRes()
}

type GetMgmtV1ProjectsByProjectIdEnvironmentsByEnvRes interface {
	getMgmtV1ProjectsByProjectIdEnvironmentsByEnvRes()
}

type GetMgmtV1ProjectsByProjectIdEnvironmentsRes interface {
	getMgmtV1ProjectsByProjectIdEnvironmentsRes()
}

type GetMgmtV1ProjectsByProjectIdFeaturesRes interface {
	getMgmtV1ProjectsByProjectIdFeaturesRes()
}

type GetMgmtV1ProjectsByProjectIdRes interface {
	getMgmtV1ProjectsByProjectIdRes()
}

type GetMgmtV1ProjectsRes interface {
	getMgmtV1ProjectsRes()
}

type GetOauth2UserinfoRes interface {
	getOauth2UserinfoRes()
}

type GetV1AccountCapabilitiesRes interface {
	getV1AccountCapabilitiesRes()
}

type GetV1AuthIdentitiesRes interface {
	getV1AuthIdentitiesRes()
}

type GetV1AuthMfaFactorsRes interface {
	getV1AuthMfaFactorsRes()
}

type GetV1AuthSessionRes interface {
	getV1AuthSessionRes()
}

type GetV1AuthWebauthnCredentialsRes interface {
	getV1AuthWebauthnCredentialsRes()
}

type GetV1HealthReadyRes interface {
	getV1HealthReadyRes()
}

type GetV1OauthGrantsRes interface {
	getV1OauthGrantsRes()
}

type GetV1OauthInteractionByInteractionIdRes interface {
	getV1OauthInteractionByInteractionIdRes()
}

type GetV1ProjectsByProjectIdAdminAccessRequestsRes interface {
	getV1ProjectsByProjectIdAdminAccessRequestsRes()
}

type GetV1ProjectsByProjectIdAdminApiKeysRes interface {
	getV1ProjectsByProjectIdAdminApiKeysRes()
}

type GetV1ProjectsByProjectIdAdminAppsByAppIdRes interface {
	getV1ProjectsByProjectIdAdminAppsByAppIdRes()
}

type GetV1ProjectsByProjectIdAdminAppsRes interface {
	getV1ProjectsByProjectIdAdminAppsRes()
}

type GetV1ProjectsByProjectIdAdminAuditLogsByAuditIdRes interface {
	getV1ProjectsByProjectIdAdminAuditLogsByAuditIdRes()
}

type GetV1ProjectsByProjectIdAdminAuditLogsRes interface {
	getV1ProjectsByProjectIdAdminAuditLogsRes()
}

type GetV1ProjectsByProjectIdAdminConfigAuthRes interface {
	getV1ProjectsByProjectIdAdminConfigAuthRes()
}

type GetV1ProjectsByProjectIdAdminConfigMfaPolicyRes interface {
	getV1ProjectsByProjectIdAdminConfigMfaPolicyRes()
}

type GetV1ProjectsByProjectIdAdminConfigPasswordPolicyRes interface {
	getV1ProjectsByProjectIdAdminConfigPasswordPolicyRes()
}

type GetV1ProjectsByProjectIdAdminConfigRateLimitsRes interface {
	getV1ProjectsByProjectIdAdminConfigRateLimitsRes()
}

type GetV1ProjectsByProjectIdAdminConfigSessionPolicyRes interface {
	getV1ProjectsByProjectIdAdminConfigSessionPolicyRes()
}

type GetV1ProjectsByProjectIdAdminConsentsRes interface {
	getV1ProjectsByProjectIdAdminConsentsRes()
}

type GetV1ProjectsByProjectIdAdminDomainsRes interface {
	getV1ProjectsByProjectIdAdminDomainsRes()
}

type GetV1ProjectsByProjectIdAdminEmailProvidersRes interface {
	getV1ProjectsByProjectIdAdminEmailProvidersRes()
}

type GetV1ProjectsByProjectIdAdminEmailTemplatesRes interface {
	getV1ProjectsByProjectIdAdminEmailTemplatesRes()
}

type GetV1ProjectsByProjectIdAdminEventsRes interface {
	getV1ProjectsByProjectIdAdminEventsRes()
}

type GetV1ProjectsByProjectIdAdminExportsByJobIdRes interface {
	getV1ProjectsByProjectIdAdminExportsByJobIdRes()
}

type GetV1ProjectsByProjectIdAdminFeaturesRes interface {
	getV1ProjectsByProjectIdAdminFeaturesRes()
}

type GetV1ProjectsByProjectIdAdminHooksRes interface {
	getV1ProjectsByProjectIdAdminHooksRes()
}

type GetV1ProjectsByProjectIdAdminI18nByLocaleRes interface {
	getV1ProjectsByProjectIdAdminI18nByLocaleRes()
}

type GetV1ProjectsByProjectIdAdminJobsByJobIdRes interface {
	getV1ProjectsByProjectIdAdminJobsByJobIdRes()
}

type GetV1ProjectsByProjectIdAdminJobsRes interface {
	getV1ProjectsByProjectIdAdminJobsRes()
}

type GetV1ProjectsByProjectIdAdminJwksRes interface {
	getV1ProjectsByProjectIdAdminJwksRes()
}

type GetV1ProjectsByProjectIdAdminOauthProvidersRes interface {
	getV1ProjectsByProjectIdAdminOauthProvidersRes()
}

type GetV1ProjectsByProjectIdAdminRetentionPolicyRes interface {
	getV1ProjectsByProjectIdAdminRetentionPolicyRes()
}

type GetV1ProjectsByProjectIdAdminRiskEventsRes interface {
	getV1ProjectsByProjectIdAdminRiskEventsRes()
}

type GetV1ProjectsByProjectIdAdminRiskRulesRes interface {
	getV1ProjectsByProjectIdAdminRiskRulesRes()
}

type GetV1ProjectsByProjectIdAdminServiceAccountsBySaIdRes interface {
	getV1ProjectsByProjectIdAdminServiceAccountsBySaIdRes()
}

type GetV1ProjectsByProjectIdAdminServiceAccountsRes interface {
	getV1ProjectsByProjectIdAdminServiceAccountsRes()
}

type GetV1ProjectsByProjectIdAdminSmsProvidersRes interface {
	getV1ProjectsByProjectIdAdminSmsProvidersRes()
}

type GetV1ProjectsByProjectIdAdminSsoConnectionsByIdRes interface {
	getV1ProjectsByProjectIdAdminSsoConnectionsByIdRes()
}

type GetV1ProjectsByProjectIdAdminSsoConnectionsByIdScimTokensRes interface {
	getV1ProjectsByProjectIdAdminSsoConnectionsByIdScimTokensRes()
}

type GetV1ProjectsByProjectIdAdminSsoConnectionsRes interface {
	getV1ProjectsByProjectIdAdminSsoConnectionsRes()
}

type GetV1ProjectsByProjectIdAdminTokenProfilesRes interface {
	getV1ProjectsByProjectIdAdminTokenProfilesRes()
}

type GetV1ProjectsByProjectIdAdminUsersByUserIdGrantsRes interface {
	getV1ProjectsByProjectIdAdminUsersByUserIdGrantsRes()
}

type GetV1ProjectsByProjectIdAdminUsersByUserIdIdentitiesRes interface {
	getV1ProjectsByProjectIdAdminUsersByUserIdIdentitiesRes()
}

type GetV1ProjectsByProjectIdAdminUsersByUserIdRes interface {
	getV1ProjectsByProjectIdAdminUsersByUserIdRes()
}

type GetV1ProjectsByProjectIdAdminUsersByUserIdSessionsRes interface {
	getV1ProjectsByProjectIdAdminUsersByUserIdSessionsRes()
}

type GetV1ProjectsByProjectIdAdminUsersRes interface {
	getV1ProjectsByProjectIdAdminUsersRes()
}

type GetV1ProjectsByProjectIdAdminWebhookDeliveriesRes interface {
	getV1ProjectsByProjectIdAdminWebhookDeliveriesRes()
}

type GetV1ProjectsByProjectIdAdminWebhooksByIdRes interface {
	getV1ProjectsByProjectIdAdminWebhooksByIdRes()
}

type GetV1ProjectsByProjectIdAdminWebhooksRes interface {
	getV1ProjectsByProjectIdAdminWebhooksRes()
}

type GetV1ScimV2ByConnectionIdGroupsByGroupIdRes interface {
	getV1ScimV2ByConnectionIdGroupsByGroupIdRes()
}

type GetV1ScimV2ByConnectionIdGroupsRes interface {
	getV1ScimV2ByConnectionIdGroupsRes()
}

type GetV1ScimV2ByConnectionIdUsersByScimUserIdRes interface {
	getV1ScimV2ByConnectionIdUsersByScimUserIdRes()
}

type GetV1ScimV2ByConnectionIdUsersRes interface {
	getV1ScimV2ByConnectionIdUsersRes()
}

type GetV1SessionsCurrentRes interface {
	getV1SessionsCurrentRes()
}

type GetV1SessionsRes interface {
	getV1SessionsRes()
}

type GetV1SsoConnectionsResolveRes interface {
	getV1SsoConnectionsResolveRes()
}

type GetV1TestMessagesRes interface {
	getV1TestMessagesRes()
}

type GetV1TokensCurrentRes interface {
	getV1TokensCurrentRes()
}

type GetV1UsersMeActivityRes interface {
	getV1UsersMeActivityRes()
}

type GetV1UsersMeConsentsRes interface {
	getV1UsersMeConsentsRes()
}

type GetV1UsersMeExportByJobIdRes interface {
	getV1UsersMeExportByJobIdRes()
}

type GetV1UsersMeRes interface {
	getV1UsersMeRes()
}

type PatchMgmtV1ProjectsByProjectIdFeaturesRes interface {
	patchMgmtV1ProjectsByProjectIdFeaturesRes()
}

type PatchMgmtV1ProjectsByProjectIdRes interface {
	patchMgmtV1ProjectsByProjectIdRes()
}

type PatchV1AuthWebauthnCredentialsByCredentialIdRes interface {
	patchV1AuthWebauthnCredentialsByCredentialIdRes()
}

type PatchV1ProjectsByProjectIdAdminApiKeysByKeyIdRes interface {
	patchV1ProjectsByProjectIdAdminApiKeysByKeyIdRes()
}

type PatchV1ProjectsByProjectIdAdminAppsByAppIdRes interface {
	patchV1ProjectsByProjectIdAdminAppsByAppIdRes()
}

type PatchV1ProjectsByProjectIdAdminConfigAuthRes interface {
	patchV1ProjectsByProjectIdAdminConfigAuthRes()
}

type PatchV1ProjectsByProjectIdAdminConfigMfaPolicyRes interface {
	patchV1ProjectsByProjectIdAdminConfigMfaPolicyRes()
}

type PatchV1ProjectsByProjectIdAdminConfigPasswordPolicyRes interface {
	patchV1ProjectsByProjectIdAdminConfigPasswordPolicyRes()
}

type PatchV1ProjectsByProjectIdAdminConfigRateLimitsRes interface {
	patchV1ProjectsByProjectIdAdminConfigRateLimitsRes()
}

type PatchV1ProjectsByProjectIdAdminConfigSessionPolicyRes interface {
	patchV1ProjectsByProjectIdAdminConfigSessionPolicyRes()
}

type PatchV1ProjectsByProjectIdAdminEmailProvidersByIdRes interface {
	patchV1ProjectsByProjectIdAdminEmailProvidersByIdRes()
}

type PatchV1ProjectsByProjectIdAdminEmailTemplatesByIdRes interface {
	patchV1ProjectsByProjectIdAdminEmailTemplatesByIdRes()
}

type PatchV1ProjectsByProjectIdAdminHooksByIdRes interface {
	patchV1ProjectsByProjectIdAdminHooksByIdRes()
}

type PatchV1ProjectsByProjectIdAdminOauthProvidersByIdRes interface {
	patchV1ProjectsByProjectIdAdminOauthProvidersByIdRes()
}

type PatchV1ProjectsByProjectIdAdminRiskRulesByRuleIdRes interface {
	patchV1ProjectsByProjectIdAdminRiskRulesByRuleIdRes()
}

type PatchV1ProjectsByProjectIdAdminServiceAccountsBySaIdRes interface {
	patchV1ProjectsByProjectIdAdminServiceAccountsBySaIdRes()
}

type PatchV1ProjectsByProjectIdAdminSmsProvidersByIdRes interface {
	patchV1ProjectsByProjectIdAdminSmsProvidersByIdRes()
}

type PatchV1ProjectsByProjectIdAdminSsoConnectionsByIdRes interface {
	patchV1ProjectsByProjectIdAdminSsoConnectionsByIdRes()
}

type PatchV1ProjectsByProjectIdAdminTokenProfilesByIdRes interface {
	patchV1ProjectsByProjectIdAdminTokenProfilesByIdRes()
}

type PatchV1ProjectsByProjectIdAdminUsersByUserIdRes interface {
	patchV1ProjectsByProjectIdAdminUsersByUserIdRes()
}

type PatchV1ProjectsByProjectIdAdminWebhooksByIdRes interface {
	patchV1ProjectsByProjectIdAdminWebhooksByIdRes()
}

type PatchV1ScimV2ByConnectionIdGroupsByGroupIdRes interface {
	patchV1ScimV2ByConnectionIdGroupsByGroupIdRes()
}

type PatchV1ScimV2ByConnectionIdUsersByScimUserIdRes interface {
	patchV1ScimV2ByConnectionIdUsersByScimUserIdRes()
}

type PatchV1SessionsBySessionIdRes interface {
	patchV1SessionsBySessionIdRes()
}

type PatchV1UsersMeRes interface {
	patchV1UsersMeRes()
}

type PostMgmtV1ProjectsByProjectIdAdminTokensRes interface {
	postMgmtV1ProjectsByProjectIdAdminTokensRes()
}

type PostMgmtV1ProjectsByProjectIdConfigApplyRes interface {
	postMgmtV1ProjectsByProjectIdConfigApplyRes()
}

type PostMgmtV1ProjectsByProjectIdConfigPlanRes interface {
	postMgmtV1ProjectsByProjectIdConfigPlanRes()
}

type PostMgmtV1ProjectsByProjectIdEnvironmentsRes interface {
	postMgmtV1ProjectsByProjectIdEnvironmentsRes()
}

type PostMgmtV1ProjectsRes interface {
	postMgmtV1ProjectsRes()
}

type PostOauth2DeviceAuthorizationRes interface {
	postOauth2DeviceAuthorizationRes()
}

type PostOauth2IntrospectRes interface {
	postOauth2IntrospectRes()
}

type PostOauth2RevokeRes interface {
	postOauth2RevokeRes()
}

type PostOauth2TokenRes interface {
	postOauth2TokenRes()
}

type PostV1AuthEmailChangeStartRes interface {
	postV1AuthEmailChangeStartRes()
}

type PostV1AuthEmailChangeVerifyRes interface {
	postV1AuthEmailChangeVerifyRes()
}

type PostV1AuthEmailVerificationStartRes interface {
	postV1AuthEmailVerificationStartRes()
}

type PostV1AuthEmailVerificationVerifyRes interface {
	postV1AuthEmailVerificationVerifyRes()
}

type PostV1AuthGuestRes interface {
	postV1AuthGuestRes()
}

type PostV1AuthIdentitiesMergeConfirmRes interface {
	postV1AuthIdentitiesMergeConfirmRes()
}

type PostV1AuthIdentitiesMergeStartRes interface {
	postV1AuthIdentitiesMergeStartRes()
}

type PostV1AuthMagicLinkStartRes interface {
	postV1AuthMagicLinkStartRes()
}

type PostV1AuthMagicLinkVerifyRes interface {
	postV1AuthMagicLinkVerifyRes()
}

type PostV1AuthMfaEmailEnrollRes interface {
	postV1AuthMfaEmailEnrollRes()
}

type PostV1AuthMfaRecoveryCodesGenerateRes interface {
	postV1AuthMfaRecoveryCodesGenerateRes()
}

type PostV1AuthMfaSmsEnrollRes interface {
	postV1AuthMfaSmsEnrollRes()
}

type PostV1AuthMfaTotpEnrollRes interface {
	postV1AuthMfaTotpEnrollRes()
}

type PostV1AuthMfaTotpVerifyRes interface {
	postV1AuthMfaTotpVerifyRes()
}

type PostV1AuthMfaVerifyRes interface {
	postV1AuthMfaVerifyRes()
}

type PostV1AuthMfaWebauthnEnrollOptionsRes interface {
	postV1AuthMfaWebauthnEnrollOptionsRes()
}

type PostV1AuthMfaWebauthnEnrollVerifyRes interface {
	postV1AuthMfaWebauthnEnrollVerifyRes()
}

type PostV1AuthOauthByProviderUnlinkRes interface {
	postV1AuthOauthByProviderUnlinkRes()
}

type PostV1AuthOtpStartRes interface {
	postV1AuthOtpStartRes()
}

type PostV1AuthOtpVerifyRes interface {
	postV1AuthOtpVerifyRes()
}

type PostV1AuthPasswordChangeRes interface {
	postV1AuthPasswordChangeRes()
}

type PostV1AuthPasswordForgotRes interface {
	postV1AuthPasswordForgotRes()
}

type PostV1AuthPasswordResetRes interface {
	postV1AuthPasswordResetRes()
}

type PostV1AuthPasswordVerifyRes interface {
	postV1AuthPasswordVerifyRes()
}

type PostV1AuthPhoneChangeStartRes interface {
	postV1AuthPhoneChangeStartRes()
}

type PostV1AuthPhoneChangeVerifyRes interface {
	postV1AuthPhoneChangeVerifyRes()
}

type PostV1AuthPhoneVerificationStartRes interface {
	postV1AuthPhoneVerificationStartRes()
}

type PostV1AuthSessionSwitchGroupRes interface {
	postV1AuthSessionSwitchGroupRes()
}

type PostV1AuthSignOutAllRes interface {
	postV1AuthSignOutAllRes()
}

type PostV1AuthSignOutRes interface {
	postV1AuthSignOutRes()
}

type PostV1AuthSignUpRes interface {
	postV1AuthSignUpRes()
}

type PostV1AuthTokenExchangeRes interface {
	postV1AuthTokenExchangeRes()
}

type PostV1AuthTokenRefreshRes interface {
	postV1AuthTokenRefreshRes()
}

type PostV1AuthWebauthnLoginVerifyRes interface {
	postV1AuthWebauthnLoginVerifyRes()
}

type PostV1AuthWebauthnRegisterOptionsRes interface {
	postV1AuthWebauthnRegisterOptionsRes()
}

type PostV1AuthWebauthnRegisterVerifyRes interface {
	postV1AuthWebauthnRegisterVerifyRes()
}

type PostV1DeviceApproveRes interface {
	postV1DeviceApproveRes()
}

type PostV1DeviceDenyRes interface {
	postV1DeviceDenyRes()
}

type PostV1OauthInteractionByInteractionIdConsentRes interface {
	postV1OauthInteractionByInteractionIdConsentRes()
}

type PostV1OauthInteractionByInteractionIdLoginRes interface {
	postV1OauthInteractionByInteractionIdLoginRes()
}

type PostV1ProjectsByProjectIdAdminAccessRequestsByIdApproveRes interface {
	postV1ProjectsByProjectIdAdminAccessRequestsByIdApproveRes()
}

type PostV1ProjectsByProjectIdAdminAccessRequestsByIdDenyRes interface {
	postV1ProjectsByProjectIdAdminAccessRequestsByIdDenyRes()
}

type PostV1ProjectsByProjectIdAdminApiKeysByKeyIdRotateRes interface {
	postV1ProjectsByProjectIdAdminApiKeysByKeyIdRotateRes()
}

type PostV1ProjectsByProjectIdAdminApiKeysRes interface {
	postV1ProjectsByProjectIdAdminApiKeysRes()
}

type PostV1ProjectsByProjectIdAdminAppsByAppIdSecretsRes interface {
	postV1ProjectsByProjectIdAdminAppsByAppIdSecretsRes()
}

type PostV1ProjectsByProjectIdAdminAppsRes interface {
	postV1ProjectsByProjectIdAdminAppsRes()
}

type PostV1ProjectsByProjectIdAdminAuditExportRes interface {
	postV1ProjectsByProjectIdAdminAuditExportRes()
}

type PostV1ProjectsByProjectIdAdminDomainsByDomainIdVerifyRes interface {
	postV1ProjectsByProjectIdAdminDomainsByDomainIdVerifyRes()
}

type PostV1ProjectsByProjectIdAdminDomainsRes interface {
	postV1ProjectsByProjectIdAdminDomainsRes()
}

type PostV1ProjectsByProjectIdAdminEmailProvidersRes interface {
	postV1ProjectsByProjectIdAdminEmailProvidersRes()
}

type PostV1ProjectsByProjectIdAdminEmailTemplatesByIdPreviewRes interface {
	postV1ProjectsByProjectIdAdminEmailTemplatesByIdPreviewRes()
}

type PostV1ProjectsByProjectIdAdminEmailTemplatesByIdSendTestRes interface {
	postV1ProjectsByProjectIdAdminEmailTemplatesByIdSendTestRes()
}

type PostV1ProjectsByProjectIdAdminEventsByEventIdReplayRes interface {
	postV1ProjectsByProjectIdAdminEventsByEventIdReplayRes()
}

type PostV1ProjectsByProjectIdAdminHooksByIdTestRes interface {
	postV1ProjectsByProjectIdAdminHooksByIdTestRes()
}

type PostV1ProjectsByProjectIdAdminHooksRes interface {
	postV1ProjectsByProjectIdAdminHooksRes()
}

type PostV1ProjectsByProjectIdAdminImportPasswordHashesVerifyRes interface {
	postV1ProjectsByProjectIdAdminImportPasswordHashesVerifyRes()
}

type PostV1ProjectsByProjectIdAdminImportUsersRes interface {
	postV1ProjectsByProjectIdAdminImportUsersRes()
}

type PostV1ProjectsByProjectIdAdminJobsByJobIdCancelRes interface {
	postV1ProjectsByProjectIdAdminJobsByJobIdCancelRes()
}

type PostV1ProjectsByProjectIdAdminJwksByKeyIdActivateRes interface {
	postV1ProjectsByProjectIdAdminJwksByKeyIdActivateRes()
}

type PostV1ProjectsByProjectIdAdminJwksRotateRes interface {
	postV1ProjectsByProjectIdAdminJwksRotateRes()
}

type PostV1ProjectsByProjectIdAdminOauthProvidersRes interface {
	postV1ProjectsByProjectIdAdminOauthProvidersRes()
}

type PostV1ProjectsByProjectIdAdminRateLimitBlocksRes interface {
	postV1ProjectsByProjectIdAdminRateLimitBlocksRes()
}

type PostV1ProjectsByProjectIdAdminRiskRulesRes interface {
	postV1ProjectsByProjectIdAdminRiskRulesRes()
}

type PostV1ProjectsByProjectIdAdminServiceAccountsBySaIdSecretsRes interface {
	postV1ProjectsByProjectIdAdminServiceAccountsBySaIdSecretsRes()
}

type PostV1ProjectsByProjectIdAdminServiceAccountsRes interface {
	postV1ProjectsByProjectIdAdminServiceAccountsRes()
}

type PostV1ProjectsByProjectIdAdminSmsProvidersRes interface {
	postV1ProjectsByProjectIdAdminSmsProvidersRes()
}

type PostV1ProjectsByProjectIdAdminSsoConnectionsByIdRotateCertificateRes interface {
	postV1ProjectsByProjectIdAdminSsoConnectionsByIdRotateCertificateRes()
}

type PostV1ProjectsByProjectIdAdminSsoConnectionsByIdScimTokensRes interface {
	postV1ProjectsByProjectIdAdminSsoConnectionsByIdScimTokensRes()
}

type PostV1ProjectsByProjectIdAdminSsoConnectionsByIdTestRes interface {
	postV1ProjectsByProjectIdAdminSsoConnectionsByIdTestRes()
}

type PostV1ProjectsByProjectIdAdminSsoConnectionsRes interface {
	postV1ProjectsByProjectIdAdminSsoConnectionsRes()
}

type PostV1ProjectsByProjectIdAdminTokenProfilesByIdPreviewRes interface {
	postV1ProjectsByProjectIdAdminTokenProfilesByIdPreviewRes()
}

type PostV1ProjectsByProjectIdAdminTokenProfilesRes interface {
	postV1ProjectsByProjectIdAdminTokenProfilesRes()
}

type PostV1ProjectsByProjectIdAdminUsersByUserIdAnonymizeRes interface {
	postV1ProjectsByProjectIdAdminUsersByUserIdAnonymizeRes()
}

type PostV1ProjectsByProjectIdAdminUsersByUserIdBanRes interface {
	postV1ProjectsByProjectIdAdminUsersByUserIdBanRes()
}

type PostV1ProjectsByProjectIdAdminUsersByUserIdExportRes interface {
	postV1ProjectsByProjectIdAdminUsersByUserIdExportRes()
}

type PostV1ProjectsByProjectIdAdminUsersByUserIdImpersonateRes interface {
	postV1ProjectsByProjectIdAdminUsersByUserIdImpersonateRes()
}

type PostV1ProjectsByProjectIdAdminUsersByUserIdMfaResetRes interface {
	postV1ProjectsByProjectIdAdminUsersByUserIdMfaResetRes()
}

type PostV1ProjectsByProjectIdAdminUsersByUserIdPasswordRes interface {
	postV1ProjectsByProjectIdAdminUsersByUserIdPasswordRes()
}

type PostV1ProjectsByProjectIdAdminUsersByUserIdSessionsRevokeRes interface {
	postV1ProjectsByProjectIdAdminUsersByUserIdSessionsRevokeRes()
}

type PostV1ProjectsByProjectIdAdminUsersByUserIdUnbanRes interface {
	postV1ProjectsByProjectIdAdminUsersByUserIdUnbanRes()
}

type PostV1ProjectsByProjectIdAdminUsersByUserIdVerifyEmailRes interface {
	postV1ProjectsByProjectIdAdminUsersByUserIdVerifyEmailRes()
}

type PostV1ProjectsByProjectIdAdminUsersByUserIdVerifyPhoneRes interface {
	postV1ProjectsByProjectIdAdminUsersByUserIdVerifyPhoneRes()
}

type PostV1ProjectsByProjectIdAdminUsersRes interface {
	postV1ProjectsByProjectIdAdminUsersRes()
}

type PostV1ProjectsByProjectIdAdminWebhookDeliveriesByDeliveryIdRetryRes interface {
	postV1ProjectsByProjectIdAdminWebhookDeliveriesByDeliveryIdRetryRes()
}

type PostV1ProjectsByProjectIdAdminWebhooksByIdRotateSecretRes interface {
	postV1ProjectsByProjectIdAdminWebhooksByIdRotateSecretRes()
}

type PostV1ProjectsByProjectIdAdminWebhooksByIdTestRes interface {
	postV1ProjectsByProjectIdAdminWebhooksByIdTestRes()
}

type PostV1ProjectsByProjectIdAdminWebhooksRes interface {
	postV1ProjectsByProjectIdAdminWebhooksRes()
}

type PostV1ScimV2ByConnectionIdGroupsRes interface {
	postV1ScimV2ByConnectionIdGroupsRes()
}

type PostV1ScimV2ByConnectionIdUsersRes interface {
	postV1ScimV2ByConnectionIdUsersRes()
}

type PostV1ServiceAccountsTokensRes interface {
	postV1ServiceAccountsTokensRes()
}

type PostV1SessionsBySessionIdTrustRes interface {
	postV1SessionsBySessionIdTrustRes()
}

type PostV1TestClockRes interface {
	postV1TestClockRes()
}

type PostV1TestResetRes interface {
	postV1TestResetRes()
}

type PostV1TestSeedRes interface {
	postV1TestSeedRes()
}

type PostV1TokensIntrospectRes interface {
	postV1TokensIntrospectRes()
}

type PostV1TokensRevokeRes interface {
	postV1TokensRevokeRes()
}

type PostV1TokensVerifyRes interface {
	postV1TokensVerifyRes()
}

type PostV1UsersMeConsentsRes interface {
	postV1UsersMeConsentsRes()
}

type PostV1UsersMeExportRes interface {
	postV1UsersMeExportRes()
}

type PutV1ProjectsByProjectIdAdminConsentsRes interface {
	putV1ProjectsByProjectIdAdminConsentsRes()
}

type PutV1ProjectsByProjectIdAdminFeaturesRes interface {
	putV1ProjectsByProjectIdAdminFeaturesRes()
}

type PutV1ProjectsByProjectIdAdminI18nByLocaleRes interface {
	putV1ProjectsByProjectIdAdminI18nByLocaleRes()
}

type PutV1ProjectsByProjectIdAdminRetentionPolicyRes interface {
	putV1ProjectsByProjectIdAdminRetentionPolicyRes()
}

type PutV1ScimV2ByConnectionIdGroupsByGroupIdRes interface {
	putV1ScimV2ByConnectionIdGroupsByGroupIdRes()
}

type PutV1ScimV2ByConnectionIdUsersByScimUserIdRes interface {
	putV1ScimV2ByConnectionIdUsersByScimUserIdRes()
}
