// Code generated by ogen, DO NOT EDIT.
package oas

type GetMgmtV1ProjectsByProjectIdConfigExportRes interface {
	getMgmtV1ProjectsByProjectIdConfigExportRes()
}

type GetOauth2AuthorizeRes interface {
	getOauth2AuthorizeRes()
}
